name: release
on:
  release:
    types: [created]

env:
  DOTNET_NOLOGO: true
  MSBUILDDISABLENODEREUSE: 1

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: set version
        run: echo "::set-env name=VERSION::${GITHUB_REF#refs/*/v}"
        shell: bash
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100-rc.1.20452.10
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.x
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - run: dotnet tool update -g dotnet-vs
      - run: echo "::set-env name=MSB::$(vs where preview --prop=InstallationPath)"
      - run: vs install preview --quiet +Microsoft.VisualStudio.Component.ManagedDesktop.Core	+Microsoft.NetCore.Component.DevelopmentTools
        if: env.MSB == ''
      - run: echo "::add-path::$(vs where preview --prop=InstallationPath)\MSBuild\Current\Bin"
      - name: build
        run: msbuild -r -p:version=$($env:VERSION)
      - name: test
        run: msbuild -t:test
      - name: pack
        run: msbuild -t:pack -p:version=$($env:VERSION)
      - name: push
        run: dotnet nuget push bin\**\*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate